In [2]:
import torch

print(torch.cuda.is_available())      # True if a CUDA GPU is usable
print(torch.cuda.device_count())      # number of GPUs
print(torch.cuda.get_device_name(0))  # e.g. "NVIDIA GeForce RTX 3060"
print(torch.version.cuda)             # CUDA version PyTorch was built with

True
1
NVIDIA GeForce RTX 4060 Laptop GPU
12.6


In [8]:
x = torch.arange(12, dtype=torch.float32)
x

tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11.])

In [9]:
x.numel()

12

In [10]:
x.shape

torch.Size([12])

In [15]:
X = x.reshape(3, -1)
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [16]:
torch.zeros((2, 3, 4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [17]:
torch.ones((2, 3, 4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [18]:
torch.randn((3,4))

tensor([[ 1.3573, -0.3354, -0.9763, -0.3307],
        [ 1.1212,  0.7277,  0.6322, -1.7278],
        [-1.1307,  0.6178, -0.9109,  0.7512]])

In [19]:
torch.tensor([[1, 2, 3], [3,2,4], [4, 5, 6]])

tensor([[1, 2, 3],
        [3, 2, 4],
        [4, 5, 6]])

In [20]:
X[-1]

tensor([ 8.,  9., 10., 11.])

In [21]:
X[1:3]

tensor([[ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])

In [22]:
X[:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

In [24]:
torch.exp(x)

tensor([162754.7969, 162754.7969, 162754.7969, 162754.7969, 162754.7969,
        162754.7969, 162754.7969, 162754.7969,   2980.9580,   8103.0840,
         22026.4648,  59874.1406])

In [26]:
x = torch.tensor([1, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])

x + y, x - y, x * y, x / y, x ** y

(tensor([ 3,  4,  6, 10]),
 tensor([-1,  0,  2,  6]),
 tensor([ 2,  4,  8, 16]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1,  4, 16, 64]))

In [28]:
X = torch.arange(12, dtype=torch.float32).reshape(3, 4)
Y = torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

torch.cat((X, Y), dim=0), torch.cat((X, Y), dim=1)

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

In [29]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

In [30]:
X.sum()

tensor(66.)

In [ ]:
a = torch.arange(12).reshape(3,4)
b = torch.arange(12).reshape(4,3)

a, b

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15]]))

In [45]:
torch.dot(a, b)

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [33]:
id(X) == id(Y)

False

In [48]:
X = torch.arange(12).reshape(3,4)

print(X)

X.sum(axis=1)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


tensor([ 6, 22, 38])

In [51]:
sum_A = X.sum(axis=1, keepdims=True)
print(X)
sum_A, sum_A.shape

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])


(tensor([[ 6],
         [22],
         [38]]),
 torch.Size([3, 1]))

In [52]:
X / sum_A

tensor([[0.0000, 0.1667, 0.3333, 0.5000],
        [0.1818, 0.2273, 0.2727, 0.3182],
        [0.2105, 0.2368, 0.2632, 0.2895]])

In [54]:
X, X.cumsum(axis=0)

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[ 0,  1,  2,  3],
         [ 4,  6,  8, 10],
         [12, 15, 18, 21]]))

In [57]:
a = torch.arange(3).reshape(3,1)
b = torch.arange(3).reshape(1,3)

b@a

tensor([[5]])